services:

  integration:
    build: .
    container_name: mqtt-integration
    volumes:
      - ./out:/certs
    environment:
      NODE_ENV: production
      NODE_CONFIG: |-
        {
          "grpc": {
            "certificates": {
              "ca_cert": "/certs/openSenseMapCA.crt",
              "server_cert": "/certs/mqtt-integration_server.crt",
              "server_key": "/certs/mqtt-integration_server.key"
            }
          },
          "openSenseMap-API-models": {
            "db": {
              "mongo_uri": "mongodb://db:27017/osem-mqtt"
            }
          }
        }

  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - ./local-redis-stack.conf:/redis-stack.conf
      - ./local-data:/data
    ports:
      - 6379:6379
      - 8001:8001

  db:
    image: mongo:5
    container_name: osem-dev-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./seeds:/seeds
      - ./scripts/osem_seed_mqtt_devices.sh:/docker-entrypoint-initdb.d/osem_seed_mqtt_devices.sh