version: "3.9"

volumes:
  mongo-data:

services:
  db:
    image: mongo:5
    container_name: osem-dev-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./seeds:/seeds
      - ./scripts/osem_seed_mqtt_devices.sh:/docker-entrypoint-initdb.d/osem_seed_mqtt_devices.sh