name: Purge Pull Request Image

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
# Run cleanup job if a new package was published or updated
on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  purge_pr_image:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Pull Request Image
        uses: vlaurin/action-ghcr-prune@v0.2.0
        with:
          token: ${{ secrets.GHCR_TOKEN}}
          organization: ${{ github.repository_owner}}
          container: ${{ github.event.repository.name }}
          tag-regex: pr-10
          dry-run: true